[package]
name = "v4l2capture-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
v4l = "0.14.0"
ctrlc = {version = "3.4.0", features = ["termination"]}
